### ISSUE TITLE
Successfully initialized but no data

### ISSUE THREAD

**Issue by travishen** [ip2location/docker-ip2location-postgresql#2]
Hi, I've tried this image out with dataset `DB1LITE`, `DB3LITE` and end up there're zero rows in the database.

#### Docker compose settings
```
  ip2location:
    container_name: ip2locationpg
    image: ip2location/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - TOKEN=xxxxxxxx
      - CODE=DB3LITE
```

### Container logs

```
ip2locationpg  |  > Create directory /_tmp [OK]
ip2locationpg  |  > Download IP2Location package  > Decompress downloaded package [OK]
ip2locationpg  |  > [PostgreSQL] Create database "ip2location_database" [OK]
ip2locationpg  |  > [PostgreSQL] Create table "ip2location_database_tmp" [OK]
ip2locationpg  |  > [PostgreSQL] Import CSV data into "ip2location_database_tmp" [OK]
ip2locationpg  |  > [PostgreSQL] Drop table "ip2location_database" 
ip2locationpg  | [OK]
ip2locationpg  |  > [PostgreSQL] Rename table "ip2location_database_tmp" to "ip2location_database" 
ip2locationpg  | [OK]
ip2locationpg  |  > [PostgreSQL] Update PostgreSQL password for user "postgres" 
ip2locationpg  | NOTICE:  function inet_to_bigint(inet) does not exist, skipping
ip2locationpg  |  > Setup completed
ip2locationpg  | 
ip2locationpg  |  > You can now connect to this PostgreSQL Server using:
ip2locationpg  | 
ip2locationpg  |    psql -h HOST -p PORT --username=postgres
ip2locationpg  |    Enter the password 'postgres' when prompted
ip2locationpg  | 
```

### Query row counts from the database

```
ip2location_database=# SELECT COUNT(*) FROM ip2location_database;
 count 
-------
     0
(1 row)
```
